interpolated:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_DEFAULT_WH') }}"
      database: "{{ env_var('SNOWFLAKE_DEFAULT_DB') }}"
      schema: "{{ env_var('DBT_DEFAULT_SCHEMA') }}"
      client_session_keep_alive: false
