version: 2

sources:
  - name: RAW
    database: "{{ env_var('SNOWFLAKE_DEFAULT_DB') }}"
    schema: RAW
    tables:
      - name: YELLOW_TRIPS
      - name: GREEN_TRIPS
      - name: TAXI_ZONE_LOOKUP

  - name: SILVER
    database: "{{ env_var('SNOWFLAKE_DEFAULT_DB') }}"
    schema: SILVER
    tables:
      - name: TRIPS_CLEAN_ALL
